config/routes.rb
Portrait::Application.routes.draw do
  resources :products

  resources :subscriptions

  resources :customers

  resources :sites

  resources :roles

  post "/users" => "users#create"
  
  devise_for :users   
   
  get "/users" => "users#index", :as => :users  
  get "/users/new" => "users#new", :as => :new_user
  get "/users/:id" => "users#show", :as => :user
  get "/users/:id/edit" => "users#edit", :as => :edit_user
  delete "/users/:id" => "users#destroy" 
  put "/users/:id" => "users#update"
 
  get "/sites/change_state/:id" => "sites#change_state", :as => :change_state

  root :to => "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_id
  # attr_accessible :title, :body
  belongs_to :role      
  has_many :sites
  belongs_to :subscription
  
  def admin?
    role.name == 'admin'
  end  
  def manager?
    role.name == 'manager'
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role_id                :integer
#  subscription_id        :integer
#

app/controllers/users_controller.rb
class UsersController < ApplicationController        
#class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout 'user'

  #skip_before_filter :require_no_authentication

  
  def index 
    @users = User.includes(:role).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])  
    #@sites = Site.submitted_portraits
    @sites = @user.sites

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    #role_id = Role.find_by_name('admin').id
    #params[:user][:role_id] = role_id
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Registration successful.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@user = User.find(params[:id])
  
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    #@user = User.find(params[:id])
    @user.destroy
  
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
end

app/views/users/_edit_form.html.haml
- #= form_for @user, :url => users_path, :html => {:method => :put} do |f|
- #= form_for @user, :method => :put do |f| 
- #= form_for @user, :url => { :action => "/update" }, :html => { :method => 'put' } do |f|  
- #= form_for @user, :html => { :method => 'put' } do |f|
= form_for @user, :method => 'put' do |f|
 - #- if @user.errors.any?
 - # = render :partial => 'shared/error_explanation', :object => @user, :as => :object

 .field
  = f.label :email
  = f.email_field :email     
 .field
  = f.label :role_id
  = f.select :role_id, Role.all.collect {|r| [r.name, r.id]}
 .field
  = f.label :password
  = f.password_field :password
 .field
  = f.label :password_confirmation
  = f.password_field :password_confirmation
 .actions
  = f.submit 'Save'

app/views/users/_form.html.haml
= form_for @user do |f|
 - #- if @user.errors.any?
 - # = render :partial => 'shared/error_explanation', :object => @user, :as => :object

 .field
  = f.label :email
  = f.email_field :email     
 .field
  = f.label :role_id
  = f.select :role_id, Role.all.collect {|r| [r.name, r.id]}
 .field
  = f.label :password
  = f.password_field :password
 .field
  = f.label :password_confirmation
  = f.password_field :password_confirmation
 .actions
  = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user
= render 'edit_form'
= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
- if @users.empty?  
 %h1 No Users
- else
 %h1 Users 
 %table
  %thead
   %tr
    %th Email
    %th Role
    %th
    %th
    %th

  %tbody
   - @users.each do |user|
    %tr
     %td= user.email  
     %td= user.role.name
     %td
      - if can? :read, User
       = link_to 'Show', user
     %td
      - if(can? :edit, user) && (user == current_user)
       = link_to 'Edit', edit_user_path(user)
     %td
      - if can? :destroy, User
       = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

 %br
 - if can? :create, User
  = link_to 'New User', new_user_path
 %br
 %br

 

app/views/users/new.html.haml
%h1 New user
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p
 %b Email:
 = @user.email
%p
 %b Role:
 = @user.role.name

= render 'shared/list_sites'


- if(can? :edit, User) && (@user == current_user)
- # - if can? :edit, User, :id => @user.id
 = link_to 'Edit', edit_user_path(@user)
 \|
- if can? :read, User
 = link_to 'Back', users_path 
- if can? :create, Site
 \|
 = link_to 'New Site', new_site_path