config/routes.rb
Portrait::Application.routes.draw do
  resources :products

  resources :subscriptions

  resources :customers

  resources :sites

  resources :roles

  post "/users" => "users#create"
  
  devise_for :users   
   
  get "/users" => "users#index", :as => :users  
  get "/users/new" => "users#new", :as => :new_user
  get "/users/:id" => "users#show", :as => :user
  get "/users/:id/edit" => "users#edit", :as => :edit_user
  delete "/users/:id" => "users#destroy" 
  put "/users/:id" => "users#update"
 
  get "/sites/change_state/:id" => "sites#change_state", :as => :change_state

  root :to => "home#index"
end

app/views/shared/_list_sites.html.haml
%table
  %tr
    %th Url
    %th Aasm state
    %th
    %th
    %th
    %th

  - @sites.each do |site|
    %tr
      %td= site.url
      %td= site.aasm_state
      %td= link_to 'Change', change_state_path(site)
      %td= link_to 'Show', site
      %td= link_to 'Edit', edit_site_path(site)
      %td= link_to 'Destroy', site, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/shared/_login.html.haml
- if user_signed_in?
  = "hi, #{current_user.email}"
%ul   
  - if user_signed_in?     
    %li= link_to 'Logout', destroy_user_session_path
  - else
    %li= link_to 'Login', new_user_session_path

app/views/shared/_menu.html.haml
- if user_signed_in? 
  %ul
    - if can? :read, User
      %li= link_to 'Users', users_path
    - if can? :read, Role
      %li= link_to 'Roles', roles_path
    - if can? :read, Site
      %li= link_to 'Sites', sites_path