config/routes.rb
Portrait::Application.routes.draw do
  resources :products

  resources :subscriptions

  resources :customers

  resources :sites

  resources :roles

  post "/users" => "users#create"
  
  devise_for :users   
   
  get "/users" => "users#index", :as => :users  
  get "/users/new" => "users#new", :as => :new_user
  get "/users/:id" => "users#show", :as => :user
  get "/users/:id/edit" => "users#edit", :as => :edit_user
  delete "/users/:id" => "users#destroy" 
  put "/users/:id" => "users#update"
 
  get "/sites/change_state/:id" => "sites#change_state", :as => :change_state

  root :to => "home#index"
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :active, :anniversary_date, :customer_id, :product_id
  has_many :products, :through => :consumptions  
  has_many :consumptions
  belongs_to :customer   
  has_one :user
end

# == Schema Information
#
# Table name: subscriptions
#
#  id               :integer          not null, primary key
#  anniversary_date :date
#  active           :boolean
#  customer_id      :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.haml
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      %ul
        - @subscription.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :anniversary_date
    = f.date_select :anniversary_date
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :customer_id
    = f.number_field :customer_id
  .actions
    = f.submit 'Save'

app/views/subscriptions/edit.html.haml
%h1 Editing subscription

= render 'form'

= link_to 'Show', @subscription
\|
= link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.haml
%h1 Listing subscriptions

%table
  %tr
    %th Anniversary date
    %th Active
    %th Product
    %th Customer
    %th
    %th
    %th

  - @subscriptions.each do |subscription|
    %tr
      %td= subscription.anniversary_date
      %td= subscription.active
      %td= subscription.product_id
      %td= subscription.customer_id
      %td= link_to 'Show', subscription
      %td= link_to 'Edit', edit_subscription_path(subscription)
      %td= link_to 'Destroy', subscription, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subscription', new_subscription_path

app/views/subscriptions/new.html.haml
%h1 New subscription

= render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.haml
%p#notice= notice

%p
  %b Anniversary date:
  = @subscription.anniversary_date
%p
  %b Active:
  = @subscription.active
%p
  %b Product:
  = @subscription.product_id
%p
  %b Customer:
  = @subscription.customer_id

= link_to 'Edit', edit_subscription_path(@subscription)
\|
= link_to 'Back', subscriptions_path